[package]
name = "wasmedge_nodejs_starter"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "my_rust_code"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.61"
