name: wasmedge-extensions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install apt-get packages
      run: |
        sudo ACCEPT_EULA=Y apt-get update
        sudo ACCEPT_EULA=Y apt-get upgrade
        sudo apt-get install wget git curl software-properties-common
    
    - name: Install Rust target
      run: |
        rustup target add wasm32-wasi
        
    - name: Install npm packages
      run: |
        npm install -g rustwasmc
        npm install wasmedge-extensions
    
    - name: Build
      run: |
        rustup override set 1.50.0
        rustwasmc build --enable-ext
      
    - name: Test
      run: |
        node node/test.js
        rustwasmc clean

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ubuntu-18.04-nodejs-${{ matrix.node-version }}
        path: node
